dbt_dskola_project2rev:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: admin
      port: 5432
      schema: project2rev
      threads: 1
      type: postgres
      user: postgres
  target: dev
