version: 2

sources:
  - name: raw_categories
  - name: raw_customers
  - name: raw_employee_territories
  - name: raw_employees
  - name: raw_order_details
  - name: raw_orders
  - name: raw_products
  - name: raw_regions
  - name: raw_shippers
  - name: raw_suppliers
  - name: raw_territories

models:
  - name: raw_categories
    description: "Staging model for raw_categories"
    tests:
      - not_null:
          - categoryID
          - categoryName
          - description
          - picture

  - name: raw_customers
    description: "Staging model for raw_customers"
    tests:
      - not_null:
          - customerID
          - companyName
          - contactName
          - contactTitle
          - address
          - city
          - region
          - postalCode
          - country
          - phone
          - fax

  - name: raw_employee_territories
    description: "Staging model for raw_employee_territories"
    tests:
      - not_null:
          - employeeID
          - territoryID

  - name: raw_employee
    description: "Staging model for raw_employee"
    tests:
      - not_null:
          - employeeID
          - lastName
          - firstName
          - title
          - titleOfCourtesy
          - birthDate
          - hireDate
          - address
          - city
          - region
          - postalCode
          - country
          - homePhone
          - extension
          - photo
          - notes
          - reportsTo
          - photoPath

  - name: raw_order_details
    description: "Staging model for raw_order_details"
    tests:
      - not_null:
          - orderID
          - productID
          - unitPrice
          - quantity
          - discount

  - name: raw_orders
    description: "Staging model for raw_orders"
    tests:
      - not_null:
          - orderID
          - customerID
          - employeeID
          - orderDate
          - requiredDate
          - shippedDate
          - shipVia
          - freight
          - shipName
          - shipAddress
          - shipCity
          - shipRegion
          - shipPostalCode
          - shipCountry

  - name: raw_products
    description: "Staging model for raw_products"
    tests:
      - not_null:
          - productID
          - productName
          - supplierID
          - categoryID
          - quantityPerUnit
          - unitPrice
          - unitsInStock
          - unitsOnOrder
          - reorderLevel
          - discontinued

  - name: raw_regions
    description: "Staging model for raw_regions"
    tests:
      - not_null:
          - regionID
          - regionDescription

  - name: raw_shippers
    description: "Staging model for raw_shippers"
    tests:
      - not_null:
          - shipperID
          - companyName
          - phone

  - name: raw_shippers
    description: "Staging model for raw_shippers"
    tests:
      - not_null:
          - supplierID
          - companyName
          - contactName
          - contactTitle
          - address
          - city
          - region
          - postalCode
          - country
          - phone
          - fax
          - homePage

  - name: raw_territories
    description: "Staging model for raw_territories"
    tests:
      - not_null:
          - territoryID
          - territoryDescription
          - regionID

 - name: fact_orders
    description: "Fact table for orders"
    tests:
      - not_null:
          - orderID
          - customerID
          - employeeID
          - orderDate
          - requiredDate
          - shippedDate
          - shipVia
          - freight
          - shipName
          - shipAddress
          - shipCity
          - shipRegion
          - shipPostalCode
          - shipCountry

  - name: fact_order_details
    description: "Fact table for order details"
    tests:
      - not_null:
          - orderID
          - productID
          - unitPrice
          - quantity
          - discount
          
  # - name: orders_detail
  #   description: "Intermediate model for order data, joining raw_orders, raw_customers, raw_products, and raw_payments"
  #   columns:
  #     - name: order_id
  #       description: "Unique identifier for each order"
  #     - name: order_date
  #       description: "Date the order was placed"
  #     - name: customer_name
  #       description: "Name of the customer who placed the order"
  #     - name: customer_email
  #       description: "Email of the customer who placed the order"
  #     - name: product_name
  #       description: "Name of the product ordered"
  #     - name: category
  #       description: "Category of the product ordered"
  #     - name: order_amount
  #       description: "Total amount of the order"
  #     - name: payment_amount
  #       description: "Amount paid for the order"
  #     - name: payment_method
  #       description: "Payment method used for the order"
  #   tests:
  #     - unique:
  #         - order_id
  #     - not_null:
  #         - order_id
  #         - order_date
  #         - customer_name
  #         - order_amount
  #         - payment_amount
